name: Run Newman Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      
      - name: Make Directory for results
        run: mkdir -p testResults
      
      - name: Run Postman Collection
        run: newman run sample-collection.json -e environment.json -r json --reporter-json-export results.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html
      
      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}

      - name: Output the run Details
        uses: actions/upload-artifact@v4
        with: 
         name: API Test Reports
         path: testResults
